# Generated by Django 3.2.7 on 2022-01-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='contenu'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
