# Generated by Django 3.2.7 on 2022-01-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220110_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='last_update',
            new_name='last_updated',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_on',
            field=models.DateField(null=True),
        ),
    ]
